current=0
foriinrange(0,len(A)):
current=i
low=0
high=len(A)
whilehigh>low:
ifA[current]<1andA[low]<1:
low=low+1
elifA[current]>0andA[high]>0:
high=high−1
elif|A[high]+A[low]|>|A[current]|:
ifA[current]>1:
low=low+1
else:
high=high−1
elif|A[high]+A[low]|<|A[current]|:
ifA[current]>1:
high=high−1
else:
low=low+1
else:
returnA[high],A[low],A[current]
iflow==current
low=low+1
ifhigh==current
high=high−1
return−1,−1,−1//Nomatchfound.